// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xanvhsbkxdierergtrud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbnZoc2JreGRpZXJlcmd0cnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjY2MTIsImV4cCI6MjA2ODM0MjYxMn0.bSHZ6sbW8SVDHcA1AS0Z89NUnmhIkFY1SSze-1_G5pU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});